project: main.o polynomial.o
	g++ main.o polynomial.o -o project

main: main.cpp polynomial.h
	g++ -c main.cpp -o main.o

polynomial: polynomial.cpp polynomial.h
	g++ -c polynomial.cpp -o polynomial.o
